routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//menambahkan database
Route::get('produk/add1', function(){
  $produk = new App\produk;
  $produk->nama_barang = "Pasta Gigi";
  $produk->harga_jual = 12000;
  $produk->diskon = 1500;
  $produk->save();
});
Route::get('produk/update1', function(){
  $produk = App\Produk::find(1);
  $produk->harga_jual = 200000;
  $produk->diskon = 2000;
  $produk->update();
});
Route::get('produk/delete1', function(){
  $produk = App\produk::find(2);
  $produk->delete();
});
Route::get('/kategori', function(){
  $kategori = App\Kategori::where('id_kategori','=', 3) -> first();
  echo "Produk untuk Kategori " . $kategori -> nama_kategori. ":";
  foreach ($kategori->produk as $data ) {
    echo "<li>" . $data->nama_barang."</li>";
  }
});
Route::get('selamat', function(){
  $produk =  App\Produk::where('id_produk', '>' , 1) -> get();
  return view ('selamat', ['nama' => 'Ichbal Yuda Backtiar', 'produk'=>$produk]);
});
Route::get('halaman1', function(){
  $title = 'Ini halaman pertama';
  $content = 'Anda sedang berada pada halaman pertama website kami';
  return view('konten.halaman1', compact('title', 'content'));
});
Route::resource('produk', 'ProdukController');

Route::get('pdfproduk', 'ProdukController@makePDF');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    //
    protected $table = 'kategori';
    protected $primaryKey = 'id_kategori';
    protected $fillable = ['nama_kategori'];

    public function produk(){
      return $this->hasMany('App\Produk', 'id_kategori');
    }
}

app/Produk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    //
    //$protected $table = 'produk';
    protected $table = 'produk';
    protected $primaryKey = 'id_produk';
    protected $fillable = ['nama_barang', 'harga_jual', 'diskon'];

    public function kategori(){
      return $this->belongsTo('App\Kategori');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Produk;
use App\Kategori;
use Redirect;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     //deklarasi properti
     protected $pesan = array('nama.required '=> 'Isi nama produk' , 'kategori.required' => 'Pilih kategori',
        'harga.required' => 'Isi harga jual', );
     protected $aturan = array('nama' => 'required',
        'kategori' => 'required',
         'harga' => 'required', );
    public function index()
    {
        //yang akan dipanggil ketika action tidak disebutkan
        //$produk = Produk::all();
        //return view('produk', ['produk' => $produk]);

        $batas =5;
        $produk = Produk::join('kategori', 'kategori.id_kategori', '=', 'produk.id_kategori')
        ->orderBy('produk.id_produk', 'desc')
        ->paginate($batas);

        $kategori = Kategori::all();

        $no = $batas * ($produk->currentPage() - 1);
        return view('produk.index', compact('produk', 'no', 'kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //untuk menambah data pada produk
        $kategori = Kategori::all();
        return view('produk.create', compact('kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //menyimpan data
        $this->validate($request, $this->aturan, $this->pesan);

        $produk = new Produk;
        $produk->nama_barang = $request['nama'];
        $produk->id_kategori = $request['kategori'];
        $produk->harga_jual = $request['harga'];
        $produk->diskon = $request['diskon'];
        $produk->save();

        return Redirect::route('produk.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //untuk edit
        $kategori = Kategori::all();
        $produk = Produk::find($id);
        return view('produk.edit', compact('kategori', 'produk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //menyimpan hasil update
        $this->validate($request, $this->aturan, $this->pesan);

        $produk = Produk::find($id);
        $produk->nama_barang = $request['nama'];
        $produk->id_kategori = $request['kategori'];
        $produk->harga_jual = $request['harga'];
        $produk->diskon = $request['diskon'];
        $produk->update();

        return Redirect::route('produk.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //untuk hapus data
        $produk = Produk::find($id);
        $produk->delete();
        return Redirect::route('produk.index');

    }

    public function makePDF(){
      $produk = Produk::join('kategori', 'kategori.id_kategori', '=', 'produk.id_kategori')
      -> orderBy('produk.id_produk', 'desc')->get();

      $no = 0;
      $pdf = 'PDF'::loadView('produk.pdf', compact('produk', 'no'));

      return $pdf->download();
    }
}

resources/views/biodata.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Biodata</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>

<br>
<br>
            <div class="content">
                <div class="title m-b-md">
                    Biodata
                </div>
                <h3>Nama : Mochammad Rizal Priyandana<h3>
                <h3>NIM  : 1931733134 <h3>
                <h3>Kelas : 2E

            </div>
        </div>
    </body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/konten/halaman1.blade.php
@extends('layouts.index')

@section('title', $title)

@section('sidebar')
  @parent
  <li>PHP</li>
@endsection

@section('content')
  <p>{{ $content }} </p>
@stop

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<h1>Layout dengan Blade</h1>

resources/views/layouts/index.blade.php
<html>
  <head>
    <title>@yield('title')</title>
  </head>
  <body>
    <header>
      @include('layouts.header')
    </header>

    <ul>
        @section('sidebar')
        <li>HTML</li>
        <li>CSS</li>
        <li>JS</li>
    @show
    </ul>

    <div class="container">
      @yield('content')
    </div>
  </body>
</html>

resources/views/produk.blade.php
<h2>Daftar Produk</h2>
<table border="1" cellspacing="0" >
    <tr>
      <th width="25%" > ID </th>
      <th width="50%" > Nama Produk </th>
      <th width="75%" > Harga </th>
    </tr>
    @foreach($produk as $data)
    <tr>
      <td align="center"> {{ $data -> id_produk }} </td>
      <td> {{ $data -> nama_barang }} </td>
      <td> {{ $data -> harga_jual }} </td>
    </tr>
    @endforeach
</table>

resources/views/produk/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Tambah Produk</h4></br>
        </div>
        <div class="panel-body">
          <form class="form-horizontal" role="form" method="post"
          action="{{ route('produk.store')}}">

          {{ csrf_field() }}
          @if($errors->any())

          <div class="alert alert-danger">
          <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul></div>
          @endif
          <div class="form-group">
            <label for = "nama" class="col-md-3 control-label"> Nama Produk</label>
            <div class="col-md-6">
              <input id="nama" type="text" class="form-control" name = "nama" autofocus="">
            </div>
          <div class="form-group">
            <label for="kategori" class="col-md-3 control-label">Kategori</label>
            <div class="col-md-6">
              <select id = "kategori" class="form-control" name="kategori">
                <option value=""> --- Pilih Kategori --- </option>
                @foreach($kategori as $list)
                <option value=" {{ $list -> id_kategori }}">
                  {{ $list -> nama_kategori }} </option>
                  @endforeach
              </select>
            </div>
          </div>

<div class="form-group">
  <label for="harga" class="col-md-3 control-label"> Harga Jual </label>
    <div class="col-md-3">
      <input id="harga" type="number" class="form-control" name="harga">
    </div>
</div>
<div class="form-group">
    <label for="diskon" class="col-md-3 control-label"> Diskon </label>
      <div class="col-md-3">
        <input id="harga" type="number" class="form-control" name="diskon">
      </div>
</div>
<div class="form-group">
  <div class="col-md-3 col-md-offset-3">
  <button type="submit" class="btn btn-primary">Simpan</button>
  <a href="{{ url('produk') }}" class="btn btn-danger"> Batal </a>
  </div>

      </div>
    </div>
  </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
@endsection

resources/views/produk/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
  <div class="row">
  <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4> Edit Produk </h4>
          </div>
          <div class="panel-body">

            <form class="form-horizontal" role="form" method="post" action="{{ route('produk.update',
            $produk->id_produk)}}">
                {{ csrf_field() }} {{ method_field('PATCH')}}

                @if($errors->any())
                <div class="alert alert-danger">
                  <ul>
                    @foreach($errors->all() as $error)
                    <li> {{ $error }} </li>
                    @endforeach
                  </ul>
                </div>
                @endif
            <div class="form-group">
              <label for="nama" class="col-md-3 control-label"> Nama Produk </label>
              <div class="col-md-6">
                <input id="nama" type="text" class="form-control" name="nama" value="{{ $produk->nama_barang }}" autofocus>
              </div>
            </div>

            <div class="form-group">
              <label for="kategori" class="col-md-3 contorl-label"> Kategori</label>
              <div class="col-md-6">
                <select id="kategori" class="form-control" name="kategori">
                  <option value=""> ---Pilih Kategori---</option>
                  @foreach($kategori as $list)

                  <option value="{{ $list->id_kategori }}" {{ $produk ->id_kategori ==
                    $list->id_kategori ? 'selected' : '' }} > {{ $list->nama_kategori }}</option>
                    @endforeach
                </select>
              </div>
            </div>

            <div class="form-group">
              <label for="nama" class="col-md-3 control-label"> Harga Jual </label>
              <div class="col-md-3">
                <input id="harga" type="number" class="form-control" name="harga" value="{{ $produk->harga_jual }}">
              </div>
            </div>

            <div class="form-group">
              <label for="diskon" class="col-md-3 control-label"> Diskon </label>
              <div class="col-md-3">
                <input id="diskon" type="number" class="form-control" name="diskon" value="{{ $produk->diskon }}">
              </div>
            </div>

            <div class="form-group">
              <div class="col-md-3 col-md-offset-3">
              <button type="submit" class="btn btn-primary">Simpan</button>
              <a href="{{ url('produk') }}" class="btn btn-danger"> Batal </a>
              </div>
</div>
</div>
<form>
</div>
</div>
</div>
</div>
@endsection

resources/views/produk/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4> Daftar Produk
            <a href="{{ route('produk.create')}}" class="btn btn-success pull-right"
            style="margin-top: -8px" > Tambah Data </a><br>
          </h4>
        </div>

        <div class="panel-body">
          <table class="table table-striped">
            <thead>
              <tr>
                <th> No </th>
                <th> Nama </th>
                <th> Kategori </th>
                <th> Harga Jual </th>
                <th> Diskon </th>
                <th> Aksi </th>
              </tr>
            </thead>
            <tbody>
              @foreach($produk as $data)

              <tr>
                <td> {{ ++$no }} </td>
                <td> {{ $data -> nama_barang }} </td>
                <td> {{ $data -> nama_kategori }} </td>
                <td> {{ $data -> harga_jual }} </td>
                <td> {{ $data -> diskon }} </td>
                <td>
                  <form method="post" action=" {{ route('produk.destroy', $data->id_produk) }}">
                    {{ csrf_field() }} {{ method_field('DELETE')}}
                    <a href="{{ route('produk.edit', $data->id_produk) }}" class = "btn btn-primary">
                      Edit</a>
                    <button type = "submit" class = "btn btn-secondary"> Hapus</button>
                  </form>
                </td>
              </tr>
              @endforeach
            </tbody>
            {{ $produk -> links()}}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/produk/pdf.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Produk PDF</title>
  </head>
  <body>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 align = "center"> Daftar Produk </h3>
      </div>
      <div class="panel-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th> No </th>
              <th> Nama Produk </th>
              <th> Kategori </th>
              <th> Harga Jual </th>
              <th> Diskon </th>
            </tr>
          </thead>
            <tbody>
              @foreach($produk as $data)

              <tr>
                <td> {{ ++$no }}</td>
                <td> {{ $data->nama_barang }}</td>
                <td> {{ $data->nama_kategori }}</td>
                <td> {{ $data->harga_jual }}</td>
                <td> {{ $data->diskon }}</td>
              </tr>
              @endforeach
            </tbody>
          </table>
    </div>
  </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/selamat.blade.php
<html>
  <head>
    <title> Welcome </title>
  </head>
  <body>
    <h3>Selamat Datang {{ $nama }}</h3>
    <p> Berikut dafatar produk yang kamu beli : </p>
    <ul>
        @foreach($produk as $data)
              <li> {{ $data->nama_barang }} </li>
        @endforeach
    </ul>
  </body>
</html>